version: '3'
services:
  wsgi:
    build:
      context: ./docker/wsgi
    volumes:
      - ./src:/usr/src/app
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/public:/usr/share/nginx/html:ro
    depends_on:
      - wsgi
    ports:
      - 80:80
